import { Inter } from "next/font/google";
import "./globals.css";

import { ProductProvider } from "@/context/productContext";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/context/CartContext";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          {/* <SignedIn> */}

          <Toaster position="top-center" />
          <ProductProvider>
            <CartProvider>{children}</CartProvider>
          </ProductProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
